config/routes.rb
Rails.application.routes.draw do
  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through

  get 'notifications/read_all', to: 'notifications#read_all',
                                    as: :read_all

  get 'notifications', to: 'notifications#index'

  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'

  resources :posts do
    resources :comments
    member do
      get 'like'
      get 'unlike'
    end
  end

  get 'browse', to: 'posts#browse', as: :browse_posts

  post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  get '/:user_name/:id/likers', to: 'posts#likers', as: :likers
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :owned_profile, only: [:edit, :update]

  def show
    @posts = User.find_by(user_name: params[:user_name]).posts.order('created_at DESC')
  end

  def edit
  end

  def update
    if @user.update(profile_params)
      flash[:success] = "Updated successfully!"
      redirect_to profile_path(@user.user_name)
    else
      @user.errors.full_messages
      flash[:error] = @user.errors.full_messages
      render :edit
    end
  end

  private

  def profile_params
    params.require(:user).permit(:avatar, :bio, :user_name)
  end

  def set_user
    @user = User.find_by(user_name: params[:user_name])
  end

  def owned_profile
    unless current_user == @user
      flash[:alert] = "That profile doesn't belong to you!"
      redirect_to root_path
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def current_user_is_following(current_user_id, followed_user_id)
    relationship = Follow.find_by(follower_id: current_user_id, following_id: followed_user_id)
    return true if relationship
  end
end

app/views/profiles/_grid_posts.html.erb
<div class="containter-fluid coverall">
  <% @posts.each do |post| %>
    <div class="col-md-4">
      <div class="posts-wrapper show-pic">
        <div class="post">
          <div class="post-head">
          </div>
            <div class="show-picture">
            <% if post.post_type == 'Image' %>
              <div class="image center-block glowing-border-image">
                <%= link_to (image_tag post.image.url(:medium), class:'img-responsive-custom'), post_path(post) %>
              </div>
            <% else %>
              <div class="image center-block glowing-border-article">
                <%= link_to (image_tag post.image.url(:medium), class:'img-responsive-custom'), post_path(post) %>
              </div>
            <% end %>
          </div>
          <div class="post-bottom">
            <div class="caption">
              <div class="caption-content">
                <p class="text-center">
                  <% if post.caption.length > 30 %>
                    <%= "#{post.caption[0..30]}..." %>
                  <% else %>
                     <%= post.caption %>
                  <% end %>
                </p>
              </div>
            </div>
            </div>
          </div>
      </div>
    </div>
  <% end %>
</div>

app/views/profiles/_profile_info.html.erb
<div class="posts-wrapper">
  <div class="row profile-header">
    <div class="col-md-6">
      <div class="img-circle">
        <%= profile_avatar_select(@user) %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="user-name-and-follow">
        <h3 class="profile-user-name">
          <%= @user.user_name %>
        </h3>
        <span>
          <% if @user == current_user %>
            <%= link_to 'Edit Profile', edit_profile_path(@user.user_name), class: 'btn edit-button' %>
          <% else %>
            <% if current_user_is_following(current_user.id, @user.id ) %>
              <%= link_to 'Following', unfollow_user_path, remote: true, class: 'btn unfollow-button', id: 'unfollow-button', method: :post %>
            <% else %>
              <%= link_to 'Follow', follow_user_path, remote: true, class: 'btn follow-button', id: 'follow-button', method: :post %>
            <% end %>
          <% end %>
        </span>
      </div>
      <div class="user-statistics text-center">
        <p>
          <%= pluralize @user.posts.count, 'post' %> | <%= pluralize @user.followers.count, 'follower' %> | <%= @user.following.count %> following
        </p>
      </div>
      <p class="profile-bio">
        <%= @user.bio %>
      </p>
    </div>
  </div>
</div>

app/views/profiles/edit.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-body">
      <div class="image-wrap">
        <%= form_for @user, url: {action: "update"}, html: { multipart: true } do |f| %>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group text-center">
                <h4>Change your profile image:</h4>
                <div class="img-circle">
                  <%= profile_avatar_select(@user) %>
                </div>
                <%= f.file_field :avatar, onChange: 'loadFile(event)' %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="text-center">
                <h4>Change Username:</h4>
                <%= f.text_area :user_name, label: false, rows: 1 %>
              </div>
              <div class="form-group text-center">
                <h4>Update your bio:</h4>
                <%= f.text_area :bio, label: false, rows: 4 %>
              </div>
            </div>
          </div>
          <div class="form-group text-center">
            <%= f.submit "Update Profile", class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/follow_user.js.erb
$('#follow-button').attr('class', 'btn unfollow-button')
                   .text('Following')
                   .attr('href', "/<%= @user.user_name %>/unfollow_user")
                   .attr('id', 'unfollow-button');

app/views/profiles/show.html.erb
<%= render "profile_info" %>
<%= render "grid_posts" %>

app/views/profiles/unfollow_user.js.erb
$('#unfollow-button').text('Follow')
                     .attr('class', 'btn follow-button')
                     .attr('href', "/<%= @user.user_name %>/follow_user")
                     .attr('id', 'follow-button');