config/routes.rb
Rails.application.routes.draw do
  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through

  get 'notifications/read_all', to: 'notifications#read_all',
                                    as: :read_all

  get 'notifications', to: 'notifications#index'

  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'

  resources :posts do
    resources :comments
    member do
      get 'like'
      get 'unlike'
    end
  end

  get 'browse', to: 'posts#browse', as: :browse_posts

  post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  get '/:user_name/:id/likers', to: 'posts#likers', as: :likers
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :notified_by, class_name: 'User'
  belongs_to :post

  validates :user_id, :notified_by_id, :identifier, :notif_type, presence: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def link_through
    @notifications = Notification.all
    @notification = Notification.find(params[:id])
    @notification.update read: true
    @notifications.each do |notification|
      if  @notification.post_id == notification.post_id
        notification.update read: true
      end
    end
    redirect_to post_path @notification.post
  end

  def read_all
    current_user.notifications.each do |notification|
      notification.update read: true
    end
    redirect_to :back
  end

  def index
    @notifications = current_user.notifications.order('created_at DESC').page(params[:page]).per(10)
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notification.html.erb
<% if notification.notif_type == 'comment' %>
  <% if notification.read %>
    <li class='comment-notif'>
      <%= link_to "#{notification.notified_by.user_name} #{notification.notif_type}ed on your post #{time_ago_in_words(notification.created_at)} ago", link_through_path(notification) %>
    </li>
  <% else %>
    <li class="unread comment-notif">
      <%= link_to "#{notification.notified_by.user_name} #{notification.notif_type}ed on your post #{time_ago_in_words(notification.created_at)} ago", link_through_path(notification) %>
    </li>
  <% end %>
<% elsif notification.notif_type == 'like' %>
  <% if notification.read %>
    <li class='like-notif'>
      <%= link_to "#{notification.notified_by.user_name} #{notification.notif_type}d your post #{time_ago_in_words(notification.created_at)} ago", link_through_path(notification) %>
    </li>
  <% else %>
    <li class="unread like-notif">
      <%= link_to "#{notification.notified_by.user_name} #{notification.notif_type}d your post #{time_ago_in_words(notification.created_at)} ago", link_through_path(notification) %>
    </li>
  <% end %>
<% else %>
  <% if notification.read %>
    <li class='like-notif'>
      <%= link_to "#{notification.notified_by.user_name} #{notification.notif_type}ed your #{time_ago_in_words(notification.created_at)} ago", link_through_path(notification) %>
    </li>
  <% else %>
    <li class="unread like-notif">
      <%= link_to "#{notification.notified_by.user_name} #{notification.notif_type}ed you #{time_ago_in_words(notification.created_at)} ago", link_through_path(notification) %>
    </li>
  <% end %>
<% end %>

app/views/notifications/_notification_dropdown.html.erb
<div class="dropdown notification-dropdown">
  <button class="btn btn-default dropdown-toggle" data-toggle="dropdown" id="dropdownMenu1" type="button" aria-haspopup="true" aria-expanded="true">
    <% if current_user.notifications.where(read: false).count > 0 %>
      <n class="count"><%= current_user.notifications.where(read: false).count %></n>
      <i class="glyphicon glyphicon-fire red" id="fire"></i>
    <% else %>
      <i class="glyphicon glyphicon-fire" id="fire"></i>
    <% end %>
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
    <div class="header-custom">
      <li class="dropdown-header text-center"> <p class='header-notif'>Notifications</p> | <p class="read-all text-center"><%= link_to 'Read All', read_all_path %></p> </li>
    </div>
    <%= render current_user.notifications.order('created_at DESC').first(15) %>
    <li class="divider" role="separator"></li>
    <li class="text-center">
      <%= link_to 'View all', notifications_path %>
    </li>
  </ul>
</div>

app/views/notifications/_notifications.html.erb
<div class='notification-item' id='notifications'>
  <% @notifications.each do |notification| %>
    <%= render 'notification', notification: notification %>
    <hr>
  <% end %>
</div>

app/views/notifications/index.html.erb
<div class="container">
  <div class="post">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="notification-stream text-center">
          <h2>Notification Stream | <%= link_to 'Read All', read_all_path %></h2>
        </div>
        <ul class="notification-index-list">
          <div>
            <%= render 'notifications' %>
          </div>
          <div class="text-center" id="paginator-notifications">
            <%= link_to_next_page @notifications, 'LOAD MORE', remote: true, id: 'load_more' %>
          </div>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/notifications/index.js.erb
$('#notifications').append("<%= escape_javascript(render 'notifications')%>");
$('#paginator-notifications').html("<%= escape_javascript(link_to_next_page(@notifications, 'LOAD MORE', remote: true, id: 'load_more'))%>");
if (!$('#load_more').length) { $('#paginator-notifications').remove(); }