config/routes.rb
Rails.application.routes.draw do
  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through

  get 'notifications/read_all', to: 'notifications#read_all',
                                    as: :read_all

  get 'notifications', to: 'notifications#index'

  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'

  resources :posts do
    resources :comments
    member do
      get 'like'
      get 'unlike'
    end
  end

  get 'browse', to: 'posts#browse', as: :browse_posts

  post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  get '/:user_name/:id/likers', to: 'posts#likers', as: :likers
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile
end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_votable

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy

  validates :user_id, :image, :caption, presence: true
  validates :caption, length: { in: 3..300 }

  has_attached_file :image, styles: { medium: "640x" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  scope :of_followed_users, -> (following_users) { where user_id: following_users }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy, :like, :unlike, :likers]
  before_action :owned_post, only: [:edit, :update, :destroy]

  def index
    @posts = Post.of_followed_users(current_user.following).order('created_at DESC').page(params[:page]).per(8)
  end

  def browse
    @posts = Post.all.order('created_at DESC').page(params[:page]).per(8)
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      if !current_user.followers.include?(current_user)
        current_user.follow(@post.user_id)
      end
      flash[:success] = "Your post has been created!"

      redirect_to posts_path
    else
      flash[:alert] = "Your new post couldn't be created! Please check the form."
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Updated successfully!"
      redirect_to post_path(@post)
    else
      flash.now[:alert] = "Post has not been updated."
      render :edit
    end
  end

  def destroy
    if @post.destroy
      flash[:success] = "Post successfully deleted!"
      redirect_to posts_path
    else
      flash.now[:alert] = "Post has not been deleted."
      render :edit
    end
  end

  def like
    if @post.liked_by current_user
      create_notification @post
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    end
  end

  def unlike
    if @post.unliked_by current_user
      notification = Notification.where(notified_by_id: current_user.id, post_id: @post.id, notif_type: 'like')
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
      if !current_user
        Notification.destroy(notification.ids[0])
      end
    end
  end

  def likers
    @likers = @post.votes_for.up.by_type(User).voters
  end

  private

  def create_notification(post)
    return if post.user.id == current_user.id
    Notification.create(user_id: post.user.id,
                        notified_by_id: current_user.id,
                        post_id: post.id,
                        identifier: post.id,
                        notif_type: 'like')
  end

  def post_params
    params.require(:post).permit(:image, :caption, :link, :post_type)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def owned_post
    unless current_user == @post.user
      flash[:alert] = "That post doesn't belong to you!"
      redirect_to root_path
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def display_likes(post)
    votes = post.votes_for.up.by_type(User)
    return list_likers(votes) if votes.size <= 8
    count_likers(votes)
  end

  def liked_post(post)
    if current_user.voted_for? post
      return link_to '', unlike_post_path(post), remote: true, id: "like_#{post.id}",
      class: "glyphicon glyphicon-heart"
    else
      link_to '', like_post_path(post), remote: true, id: "like_#{post.id}",
      class: "glyphicon glyphicon-heart-empty"
    end
  end

  private

  def list_likers(votes)
    user_names = []
    unless votes.blank?
      votes.voters.each do |voter|
        user_names.push(link_to voter.user_name, profile_path(voter.user_name), class: 'user-name')
      end
      user_names.to_sentence.html_safe + like_plural(votes)
    end
  end

  def count_likers(votes)
    vote_count = votes.size
    vote_count.to_s + ' likes'
  end

  def like_plural(votes)
    return 'like this' if votes.count > 1
    'likes this'
  end
end

app/views/posts/_article_posts.html.erb
<% @posts.each do |post| %>
  <% if post.post_type == 'Article' %>
    <%= render 'post', post: post %>
  <% end %>
<% end %>

app/views/posts/_form.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-body">
      <div class="image-wrap">
        <%= form_image_select(@post) %>
        <%= simple_form_for @post, html: { multipart: true } do |f| %>
          <div class="row">
            <div class="col-md-12 text-center">
              <%= f.error_notification %>
            </div>
          </div>
          <div class="container-fluid">
            <div class="form-group text-center">
              <h4>Upload an image (this is required):</h4>
              <%= f.input :image, label: false, input_html: { onChange: 'loadFile(event)' } %>
            </div>
            <div class="form-group text-center collection">
              <%= f.input :post_type, collection: ['Article', 'Image'] %>
            </div>
            <div class="form-group text-center">
              <%= f.input :link, label: false, placeholder: 'Link to article' %>
            </div>
            <div class="form-group text-center">
              <%= f.input :caption, label: false, placeholder: 'Add your caption' %>
            </div>
            <div class="form-group text-center">
              <%= f.button :submit, class: 'btn-success btn-block' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/_likes.html.erb
<div class="likes" id="likes_<%= post.id %>">
  <% if post.votes_for.up.size < 8 %>
    <%= display_likes post %>
  <% else %>
    <%= link_to display_likes(post), likers_path(post.user.user_name, post.id) %>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class="posts-wrapper row">
  <div class="post">
    <div class="post-head">
      <div class="thumb-img">
        <% if post.post_type == 'Image' %>
          <div class="post-type-image">
            <%= link_to post.post_type, post_path(post) %>
          </div>
        <% else %>
          <div class="post-type-article">
            <%= link_to 'Discussion', post_path(post) %> | <%= link_to post.post_type, post.link %>
          </div>
        <% end %>
        <div class="user-name">
          <%= link_to post.user.user_name, profile_path(post.user.user_name) %>
        </div>
      </div>
    </div>

    <% if post.post_type == 'Image' %>
      <div class="image center-block glowing-border-image">
        <%= link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post) %>
      </div>
    <% else %>
      <div class="image center-block glowing-border-article">
        <%= link_to (image_tag post.image.url(:medium), class:'img-responsive'), post.link %>
      </div>
    <% end %>

    <div class="post-bottom">
      <%= render 'posts/likes', post: post %>
      <div class="caption">
        <div class="caption-content">
          <div class="user-name">
            <%= link_to post.user.user_name, profile_path(post.user.user_name) %>
          </div>
          <%= post.caption %>
        </div>
      </div>
      <div class="comments" id="comments_<%= post.id %>">
        <% if post.comments.any? %>
          <%= render post.comments.last(4), post: post %>
        <% end %>
      </div>
      <div class="paginator" id="#comments-paginator-<%= post.id %>">
        <% unless post.comments.count <= 4 %>
          <%= link_to "view all #{post.comments.count} comments", post_comments_path(post), remote: true, class: 'more-comments', data: {post_id: "#{post.id}", type: "html"} %>
        <% end %>
        <div class="time-ago">
          <p><%= "posted #{time_ago_in_words(post.created_at)} ago" %></p>
        </div>
      </div>
      <div class="comment-like-form row">
        <div class="col-sm-1 like-button">
          <%= liked_post post %>
        </div>
        <div class="comment-form col-sm-11">
          <%= form_for([post, post.comments.build], remote: true) do |f| %>
            <%= f.text_field :content, placeholder: 'Add comment', class: "comment_content", id: "comment_content_#{post.id}" %>
            <%= f.button "Submit Comment", class: 'btn-success btn-block', id: 'comment_submit' %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="text-center">
      <% if post.user.id == current_user.id %>
        <%= link_to 'Edit Post', edit_post_path(post) %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/_post_dashboard.html.erb
<div id="posts">
  <%= render 'posts' %>
</div>
<div class="text-center" id="paginator">
  <%= link_to_next_page @posts, 'LOAD MORE', remote: true, id: 'load_more' %>
</div>

app/views/posts/_post_dashboard.js.erb
$('#posts').append("<%= escape_javascript(render 'posts')%>");
$('#paginator').html("<%= escape_javascript(link_to_next_page(@posts, 'LOAD MORE', remote: true, id: 'load_more'))%>");
if (!$('#load_more').length) { $('#paginator').remove(); }

app/views/posts/_posts.html.erb
<% @posts.each do |post| %>
  <%= render 'post', post: post %>
<% end %>

app/views/posts/browse.html.erb
<%= render 'post_dashboard', posts: @posts %>

app/views/posts/edit.html.erb
<%= render 'form' %>
<div class="text-center">
  <%= button_to 'Delete Post', post_path(@post), method: :delete,
  data: { confirm: "Are you sure you want to delet this?"} %>
</div>

app/views/posts/index.html.erb
<%= render 'post_dashboard' %>

app/views/posts/like.js.erb
$("#like_<%= @post.id %>").removeClass('glyphicon-heart-empty').addClass('glyphicon-heart');
$("#like_<%= @post.id %>").removeAttr('href').attr('href', '/posts/<%= @post.id %>/unlike');
$("#likes_<%= @post.id %>").html("<%= j (render partial: 'posts/likes', locals: { post: @post} ) %>");

app/views/posts/likers.html.erb
<div class="container">
  <div class="post">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="notification-stream text-center">
          <h2><%= "Liked your post" %></h2>
        </div>
        <ul class="likers-index-list">
          <div class='liker-item'>
            <% @likers.each do |liker| %>
              <%= link_to liker.user_name, profile_path(liker.user_name) %>
              <hr>
            <% end %>
          </div>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/unlike.js.erb
$("#like_<%= @post.id %>").removeClass('glyphicon-heart').addClass('glyphicon-heart-empty');
$("#like_<%= @post.id %>").removeAttr('href').attr('href', '/posts/<%= @post.id %>/like');
$("#likes_<%= @post.id %>").html("<%= j (render partial: 'posts/likes', locals: { post: @post} ) %>");