config/routes.rb
Rails.application.routes.draw do
  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through

  get 'notifications/read_all', to: 'notifications#read_all',
                                    as: :read_all

  get 'notifications', to: 'notifications#index'

  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'

  resources :posts do
    resources :comments
    member do
      get 'like'
      get 'unlike'
    end
  end

  get 'browse', to: 'posts#browse', as: :browse_posts

  post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user

  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  get '/:user_name/:id/likers', to: 'posts#likers', as: :likers
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile
end

app/views/layouts/_nav_left.html.erb
<div class="navbar-header">
  <button class="navbar-toggle collapsed" data-target="#bs-navbar-collapse-1" data-toggle="collapse" type="button">
    <span class="sr-onlyToggle">Navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <div class="navbar-brand">
    <%= link_to "MyStream", root_path %>
    <% if user_signed_in? %>
    <%= "::" %>
    <%= link_to "#{current_user.user_name}", profile_path(current_user.user_name) %>
    <% end %>
  </div>
</div>

app/views/layouts/_nav_right.html.erb
<div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
  <ul class="nav navbar-nav navbar-right">
    <% if user_signed_in? %>
      <li>
        <%= render 'notifications/notification_dropdown' %>
      </li>
      <li>
        <%= link_to browse_posts_path, class: "btn btn-default navbtn" do %>
        <i class="glyphicon glyphicon-list-alt"></i><br>
        <n class="nav-text">AllStream</n>
        <% end %>
      </li>
      <li>
        <%= link_to posts_path, class: "btn btn-default navbtn" do %>
        <i class="glyphicon glyphicon-list"></i><br>
        <n class="nav-text">MyStream</n>
        <% end %>
      </li>
      <li>
        <%= link_to new_post_path, class: "btn btn-default navbtn" do %>
        <i class="glyphicon glyphicon-camera"></i><br>
        <n class="nav-text">New Post</n>
        <% end %>
      </li>
      <li>
        <%= link_to destroy_user_session_path, method: :delete, class: "btn btn-default navbtn" do %>
        <i class="glyphicon glyphicon-log-out"></i><br>
        <n class="nav-text">Logout</n>
        <% end %>
      </li>
    <% else %>
      <li>
        <%= link_to "Login", new_user_session_path %>
      </li>
      <li>
        <%= link_to "Register", new_user_registration_path %>
    </li>
    <% end %>
  </ul>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="navbar-container">
  <%= render "layouts/nav_left" %>
  <%= render "layouts/nav_right" %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyStream</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render "layouts/navbar" %>

    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: [:alert, alert_for(name)] %>
      <% end %>
    </div>
    <%= yield %>

  </body>
</html>